<?php
session_start();
require_once __DIR__ . '/db.php';

function generate_certificate_pdf_file($certificate)
{
    $tmp_html = tempnam(sys_get_temp_dir(), 'cert_html_');
    $tmp_pdf  = tempnam(sys_get_temp_dir(), 'cert_pdf_');

    if ($tmp_html === false || $tmp_pdf === false) {
        return false;
    }

    $name = htmlspecialchars((string)($certificate['student_name'] ?? 'Student'), ENT_QUOTES, 'UTF-8');
    $exam = htmlspecialchars((string)($certificate['exam_type'] ?? 'Certificate'), ENT_QUOTES, 'UTF-8');
    $score = (int)($certificate['score'] ?? 0);
    $total = (int)($certificate['total_questions'] ?? 0);
    $issued = date('Y-m-d', strtotime((string)($certificate['issued_at'] ?? 'now')));
    $verify = 'VC-' . str_pad((string)($certificate['id'] ?? 0), 6, '0', STR_PAD_LEFT);

    $html = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Certificate</title>
  <style>
    body { margin: 0; font-family: Arial, Helvetica, sans-serif; background: #fff; color: #111827; }
    .page { width: 900px; min-height: 1200px; margin: 0 auto; padding: 48px 56px; box-sizing: border-box; border: 8px solid #8b5cf6; border-radius: 24px; background: linear-gradient(180deg, #ffffff 0%, #f5f3ff 100%); }
    .topbar { display: flex; align-items: center; justify-content: center; gap: 12px; margin-bottom: 14px; }
    .logo { width: 54px; height: 54px; border-radius: 14px; background: linear-gradient(135deg, #7c3aed, #a78bfa); color: #fff; display: grid; place-items: center; font-size: 22px; font-weight: bold; box-shadow: 0 10px 18px rgba(124,58,237,0.25); }
    .brand { font-size: 16px; letter-spacing: 3px; color: #6d28d9; text-transform: uppercase; font-weight: bold; }
    .badge { text-align: center; font-size: 13px; letter-spacing: 4px; text-transform: uppercase; color: #7c3aed; margin-bottom: 10px; }
    h1 { text-align: center; font-size: 42px; margin: 8px 0 8px; color: #111827; }
    .sub { text-align: center; font-size: 18px; color: #4b5563; margin-bottom: 8px; }
    h2 { text-align: center; font-size: 32px; margin: 14px 0 10px; color: #111827; }
    p { text-align: center; font-size: 18px; line-height: 1.6; margin: 8px 0; }
    .name { font-size: 38px; font-weight: bold; color: #111827; margin: 18px 0; }
    .highlight { display: inline-block; padding: 6px 10px; border-radius: 999px; background: #ede9fe; color: #5b21b6; font-size: 14px; font-weight: bold; }
    .meta { font-size: 16px; color: #374151; }
    .line { height: 2px; width: 180px; background: linear-gradient(90deg, #c4b5fd, #7c3aed); margin: 18px auto; }
    .footer { margin-top: 44px; font-size: 14px; color: #4b5563; text-align: center; }
    .sign { margin-top: 52px; display: flex; justify-content: space-between; font-size: 14px; color: #374151; }
    .sign .box { width: 220px; border-top: 1px solid #cbd5e1; padding-top: 8px; text-align: center; }
  </style>
</head>
<body>
  <div class="page">
    <div class="badge">Official Certificate</div>
    <h1>Certificate of Completion</h1>
    <p>This certificate is proudly awarded to</p>
    <h2 class="name">$name</h2>
    <p>for successfully completing the <strong>$exam</strong> assessment with <strong>$score / $total</strong> marks.</p>
    <p class="meta">Issued on: $issued &nbsp; | &nbsp; Verification Number: $verify</p>
    <p class="footer">Generated by Sofyias Learning Platform</p>
  </div>
</body>
</html>
HTML;

    file_put_contents($tmp_html, $html);

    $browser = 'C:\Program Files\Google\Chrome\Application\chrome.exe';
    if (!is_file($browser)) {
        $browser = 'C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe';
    }

    if (!is_file($browser)) {
        @unlink($tmp_html);
        @unlink($tmp_pdf);
        return false;
    }

    $command = '"' . str_replace('"', '\"', $browser) . '" --headless --disable-gpu --no-sandbox --print-to-pdf="' . str_replace('"', '\"', $tmp_pdf) . '" "' . str_replace('"', '\"', $tmp_html) . '"';
    exec($command, $output, $code);

    @unlink($tmp_html);

    if ($code !== 0 || !is_file($tmp_pdf) || filesize($tmp_pdf) === 0) {
        @unlink($tmp_pdf);
        return false;
    }

    return $tmp_pdf;
}

$is_admin = isset($_SESSION['admin_id']);
$is_student = isset($_SESSION['student_id']);

if (!$is_admin && !$is_student) {
    header('Location: student_login.php');
    exit;
}

$message = '';
$error = '';

try {
    $pdo->exec('CREATE TABLE IF NOT EXISTS certificates (
        id INT AUTO_INCREMENT PRIMARY KEY,
        student_id VARCHAR(100) NOT NULL,
        student_name VARCHAR(255) NOT NULL,
        exam_type VARCHAR(50) NOT NULL,
        score INT NOT NULL DEFAULT 0,
        total_questions INT NOT NULL DEFAULT 0,
        issued_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        UNIQUE KEY uq_certificate (student_id, exam_type)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci');
} catch (PDOException $e) {
    $error = 'Certificate table setup failed: ' . $e->getMessage();
}

if (isset($_GET['issue'])) {
    $submission_id = (int)$_GET['issue'];
    try {
        $stmt = $pdo->prepare('SELECT student_id, student_name, exam_type, score, total_questions FROM exam_submissions WHERE id = :id');
        $stmt->execute([':id' => $submission_id]);
        $row = $stmt->fetch();

        if (!$row) {
            $error = 'ይህ ፈተና ውጤት አልተገኘም።';
        } else {
            $stmt = $pdo->prepare('INSERT IGNORE INTO certificates (student_id, student_name, exam_type, score, total_questions) VALUES (:student_id, :student_name, :exam_type, :score, :total_questions)');
            $stmt->execute([
                ':student_id' => $row['student_id'],
                ':student_name' => $row['student_name'],
                ':exam_type' => $row['exam_type'],
                ':score' => (int)$row['score'],
                ':total_questions' => (int)$row['total_questions'],
            ]);
            $message = 'ሰርቲፊኬት ተለቋል።';
        }
    } catch (PDOException $e) {
        $error = 'ስህተት: ' . $e->getMessage();
    }
}

if (isset($_GET['delete'])) {
    $cert_id = (int)$_GET['delete'];
    try {
        $stmt = $pdo->prepare('DELETE FROM certificates WHERE id = :id');
        $stmt->execute([':id' => $cert_id]);
        $message = 'ሰርቲፊኬት ተሰርዟል።';
    } catch (PDOException $e) {
        $error = 'ስህተት: ' . $e->getMessage();
    }
}

if (!$is_admin && !isset($_GET['download'])) {
    header('Location: student_dashboard.php');
    exit;
}

try {
    $stmt = $pdo->query('SELECT es.*, s.email FROM exam_submissions es LEFT JOIN students s ON s.student_id = es.student_id ORDER BY es.submitted_at DESC');
    $submissions = $stmt->fetchAll();
} catch (PDOException $e) {
    $submissions = [];
    $error = 'DB ችግኝ አለ። ' . $e->getMessage();
}

try {
    $stmt = $pdo->query('SELECT COUNT(*) as total_certificates FROM certificates');
    $dashboard_certificate_count = (int)($stmt->fetch()['total_certificates'] ?? 0);
} catch (PDOException $e) {
    $dashboard_certificate_count = 0;
}

try {
    $stmt = $pdo->query('SELECT * FROM certificates ORDER BY issued_at DESC');
    $certificates = $stmt->fetchAll();
} catch (PDOException $e) {
    $certificates = [];
}

if (isset($_GET['download'])) {
    $cert_id = (int)$_GET['download'];
    try {
        if ($is_student) {
            $stmt = $pdo->prepare('SELECT * FROM certificates WHERE id = :id AND student_id = :student_id');
            $stmt->execute([':id' => $cert_id, ':student_id' => $_SESSION['student_id']]);
        } else {
            $stmt = $pdo->prepare('SELECT * FROM certificates WHERE id = :id');
            $stmt->execute([':id' => $cert_id]);
        }
        $certificate = $stmt->fetch();

        if ($certificate) {
            $pdf_path = generate_certificate_pdf_file($certificate);
            if ($pdf_path !== false) {
                header('Content-Type: application/pdf');
                header('Content-Disposition: attachment; filename="certificate-' . (int)$cert_id . '.pdf"');
                header('Content-Length: ' . filesize($pdf_path));
                readfile($pdf_path);
                unlink($pdf_path);
                exit;
            }
            $error = 'PDF ማውረድ አልተቻለም። የብራውዘር እገዳ እና ቪዛውን ይመልከቱ።';
        } else {
            $error = 'ይህ ሰርቲፊኬት አልተገኘም።';
        }
    } catch (PDOException $e) {
        $error = 'ስህተት: ' . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="am">
<head>
    <meta charset="UTF-8">
    <title>የሰርቲፊኬት አስተዳደር</title>
    <style>
        * { box-sizing: border-box; }
        body { margin: 0; font-family: Arial, sans-serif; background: #f5f7fa; color: #1f2937; }
        .topbar { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 14px 18px; display: flex; justify-content: space-between; align-items: center; }
        .topbar a { color: white; text-decoration: none; background: rgba(255,255,255,0.12); padding: 8px 12px; border-radius: 6px; }
        .wrap { max-width: 1200px; margin: 24px auto; padding: 0 18px; }
        .card { background: white; border-radius: 10px; box-shadow: 0 4px 16px rgba(0,0,0,0.08); padding: 18px; margin-bottom: 18px; }
        .msg { padding: 10px 12px; border-radius: 6px; margin-bottom: 12px; }
        .msg.ok { background: #d4f1d8; color: #1d6a2b; }
        .msg.err { background: #ffe7e7; color: #a41616; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border-bottom: 1px solid #e5e7eb; padding: 10px; text-align: left; vertical-align: top; }
        th { background: #eef2ff; }
        .btn { display: inline-block; padding: 7px 10px; border-radius: 6px; text-decoration: none; font-size: 12px; }
        .btn.issue { background: #667eea; color: white; }
        .btn.del { background: #e74c3c; color: white; }
    </style>
</head>
<body>
<div class="topbar">
    <h2 style="margin: 0;">📜 የሰርቲፊኬት አስተዳደር</h2>
    <a href="admin_dashboard.php">ወደ ዳሽቦርድ</a>
</div>
<div class="wrap">
    <div class="card">
        <h3>እንዴት ይሰራል</h3>
        <p>ከፈተና ውጤቶች ውስጥ የሚገኙትን ተማሪዎች በአንድ ጠቅላላ ቁጥር ሰርቲፊኬት ለመስጠት እዚህ ይቆጣጠሩ። እንዲሁም የተሰጡትን ሰርቲፊኬቶች እዚህ ማስተካከል ወይም መሰረዝ ይችላሉ።</p>
        <p><strong>የአሁኑ ሰርቲፊኬት ቆጣሪ:</strong> <?php echo $dashboard_certificate_count; ?></p>
        <?php if ($message): ?><div class="msg ok"><?php echo safe($message); ?></div><?php endif; ?>
        <?php if ($error): ?><div class="msg err"><?php echo safe($error); ?></div><?php endif; ?>
    </div>

    <div class="card">
        <h3>ለማስተላለፍ ዝግጁ የሆኑ ውጤቶች</h3>
        <table>
            <thead>
                <tr>
                    <th>ተማሪ</th>
                    <th>ኢሜይል</th>
                    <th>ፈተና</th>
                    <th>ውጤት</th>
                    <th>ድርጊት</th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($submissions)): ?>
                    <tr><td colspan="5">ምንም የፈተና ውጤት የለም።</td></tr>
                <?php else: foreach ($submissions as $row): ?>
                    <tr>
                        <td><?php echo safe($row['student_name']); ?></td>
                        <td><?php echo safe($row['email'] ?? '-'); ?></td>
                        <td><?php echo safe($row['exam_type']); ?></td>
                        <td><?php echo (int)$row['score']; ?> / <?php echo (int)$row['total_questions']; ?></td>
                        <td><a class="btn issue" href="admin_certificate.php?issue=<?php echo (int)$row['id']; ?>">ሰርቲፊኬት ለመስጠት</a></td>
                    </tr>
                <?php endforeach; endif; ?>
            </tbody>
        </table>
    </div>

    <div class="card">
        <h3>የተሰጡ ሰርቲፊኬቶች</h3>
        <table>
            <thead>
                <tr>
                    <th>ተማሪ</th>
                    <th>ፈተና</th>
                    <th>ውጤት</th>
                    <th>ቀን</th>
                    <th>ድርጊት</th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($certificates)): ?>
                    <tr><td colspan="5">ምንም ሰርቲፊኬት አልተሰጠም።</td></tr>
                <?php else: foreach ($certificates as $row): ?>
                    <tr>
                        <td><?php echo safe($row['student_name']); ?></td>
                        <td><?php echo safe($row['exam_type']); ?></td>
                        <td><?php echo (int)$row['score']; ?> / <?php echo (int)$row['total_questions']; ?></td>
                        <td><?php echo safe($row['issued_at']); ?></td>
                        <td>
                            <a class="btn issue" href="admin_edit_certificate.php?id=<?php echo (int)$row['id']; ?>">አስተካከል</a>
                            <a class="btn del" href="admin_certificate.php?delete=<?php echo (int)$row['id']; ?>" onclick="return confirm('ይህን ሰርቲፊኬት ሰርዝ?');">ሰርዝ</a>
                        </td>
                    </tr>
                <?php endforeach; endif; ?>
            </tbody>
        </table>
    </div>
</div>
</body>
</html>
